### ISSUE TITLE
Errors information missing from readme

### ISSUE THREAD

**Issue by tisAliG** [ryanfitzer/comment-serializer#2]
Please, kind sir, add some documentation on how you deal with errors.

**Comment by ryanfitzer** [comment]
TODO: add to the API to easily extract errors. Example: https://github.com/ryanfitzer/comment-serializer/blob/722a710f99e0074e90a235f5ea552fa9e78833a9/runme.js#L26

**Comment by ryanfitzer** [comment]
Fixed in [10a90b0](https://github.com/ryanfitzer/comment-serializer/commit/10a90b032a26c32938bb23d9819102d40c83caed#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R157)
